### ISSUE TITLE
scaleType的疑问

### ISSUE THREAD

**Issue by iielse** [meikaiss/giftvideoplayer#5]
我试了一下 感觉你这个 GiftVideoView 里面的 CENTER_INSIDE  对应的效果其实是 fitCenter。

**Comment by meikaiss** [comment]
有可能，缩放模式这一块逻辑我没有仔细整理，主要精力放在了opengl的图像合成。不过，基本fitCenter就满足实际需求，以后有空有需要了再整理缩放模式吧。

**Comment by iielse** [comment]
是的，就是你那个名字有点误导，直接原地把名字换成 FIT_CENTER 就好

**Comment by iielse** [comment]
就把名字改下， scaleType 【 centerCrop/fitCenter/fitXY】 3个就够了.不需要在拓展.
